services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: secx-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: secx
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    networks:
      - secx-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d secx"]
      interval: 10s
      timeout: 5s
      retries: 5

# Volumes persistentes
volumes:
  postgres_data:
    driver: local

networks:
  secx-network:
    driver: bridge
